import 'package:beisbol/models/preguntaModel.dart';

class PreguntasConst {
  PreguntasConst._();

  static List<Pregunta> preguntas = [
    //********************************* TITO ************************************************
    //hits
    Pregunta(
      idLibro: 1,
      idPregunta: 1,
      contestada: false,
      pregunta: '¿Quién escribió la carta de Tito?',
      cita: 'Tito 1:1',
      valor: 1,
      respuesta: 'Pablo'
    ),
    Pregunta(
      idLibro: 1,
      idPregunta: 2,
      contestada: false,
      pregunta: '¿Qué nos prometió Dios desde antes de los siglos?',
      respuesta: 'Vida eterna',
      valor: 1,
      cita: 'Tito 1:2',
    ),
    Pregunta(
      idLibro: 1,
      idPregunta: 3,
      contestada: false,
      pregunta: '¿Qué manifestó Dios a su tiempo?',
      cita: 'Tito 1:3',
      respuesta: 'Su palabra',
      valor: 1,
    ),
    Pregunta(
      idLibro: 1,
      idPregunta: 4,
      contestada: false,
      pregunta: '¿Qué se dice en Tito 1:2 referente a lo que Dios "NO hace"?',
      cita: 'Tito 1:2',
      respuesta: 'Mentir',
      valor: 1,
    ),
    //dobles
    Pregunta(
      idLibro: 1,
      idPregunta: 5,
      contestada: false,
      pregunta: '¿Desde cuándo prometió Dios la esperanza de la vida eterna?',
      cita: 'Tito 1:2',
      respuesta: 'Desde antes del principio de los siglos',
      valor: 2,
    ),
    Pregunta(
      idLibro: 1,
      idPregunta: 6,
      contestada: false,
      pregunta: '''¿Cómo se describe a Tito en "Tito 1:4"?\n'''
      '''A) Creyente fiel y amado por Dios.\n'''
      '''B) Interprete de la ley.\n'''
      '''C) Varón prudente, integro, serio, sano e ireprochable.\n'''
      '''D) Verdadero hijo en la común fé.''',
      cita: 'Tito 1:4',
      respuesta: 'D',
      valor: 1,
    ),
    //triples
    Pregunta(
      idLibro: 1,
      idPregunta: 7,
      contestada: false,
      pregunta: '¿En qué ciudad había dejado Pablo a Tito?',
      cita: 'Tito 1:5',
      respuesta: 'En Creta',
      valor: 3,
    ),
    Pregunta(
      idLibro: 1,
      idPregunta: 8,
      contestada: false,
      pregunta: 'Diga 5 requisitos para ser Obispo.',
      cita: 'Tito 1:6-9',
      respuesta: '---',
      valor: 3,
    ),
    //home run
    Pregunta(
      idLibro: 1,
      idPregunta: 9,
      contestada: false,
      pregunta: 'Diga las 2 razones por la cual Pablo dejó a Tito en Creta',
      cita: 'Tito 1:5',
      respuesta: '1. Corregir lo deficiente.\n 2. Establecer ancianos en cada ciudad.',
      valor: 4,
    ),
    Pregunta(
      idLibro: 1,
      idPregunta: 10,
      contestada: false,
      pregunta: 'Diga 7 requisitos para ser Obispo.',
      cita: 'Tito 1:6-9',
      respuesta: '---',
      valor: 4,
    ),

    //hits
    Pregunta(
      idPregunta: 11,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cuál fue el medio utilizado por Dios para manifestar su palabra?\n'''
      '''A) Los sueños.\n'''
      '''B) La predicación.\n''',
      cita: 'Tito 1:3',
      respuesta: 'B',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 12,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Quién encomendó a Pablo la tarea de predicar el evangelio?\n'''
      '''A) Dios.\n'''
      '''B) Los Fariseos.\n''',
      cita: 'Tito 1:3',
      respuesta: 'A',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 13,
      idLibro: 1,
      contestada: false,
      pregunta: '''Un anciano debe ser irreprensible. ¿Verdadero o Falso?\n''',
      cita: 'Tito 1:6',
      respuesta: 'Verdadero',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 14,
      idLibro: 1,
      contestada: false,
      pregunta: '''Los ancianos de la iglesia pueden ser maridos de varias mujeres. ¿Verdadero o Falso?\n''',
      cita: 'Tito 1:6',
      respuesta: 'Falso',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 15,
      idLibro: 1,
      contestada: false,
      pregunta: '''Cada congregación debe tener solamente un Anciano en el liderazgo. ¿Verdadero o Falso?\n''',
      cita: 'Tito 1:5',
      respuesta: 'Falso',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 16,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Quién era el responsable de establecer los ancianos y obispos, en cada ciudad de Creta?\n'''
      '''A) Zenas.\n'''
      '''B) Tito.\n''',
      cita: 'Tito 1:5',
      respuesta: 'B',
      valor: 1,
    ),
     Pregunta(
      idPregunta: 17,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Es correcto nombrar como Obispo a alguien soberbio?\n''',
      cita: 'Tito 1:7',
      respuesta: 'NO',
      valor: 1,
    ),
     Pregunta(
      idPregunta: 18,
      idLibro: 1,
      contestada: false,
      pregunta: '''Un Obispo debe ser:\n'''
      '''A) Hospedador y santo\n'''
      '''B) Dado al vino y pendenciero\n'''
      '''C) Dueño de sí mismo y sobrio\n'''
      '''D) Todas las anteriores\n'''
      '''E) A Y C\n''',
      cita: 'Tito 1:7-8',
      respuesta: 'E',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 19,
      idLibro: 1,
      contestada: false,
      pregunta: '''Un Obispo NO puede ser:\n'''
      '''A) Hospedador\n'''
      '''B) Pendenciero\n''',
      cita: 'Tito 1:7',
      respuesta: 'B',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 20,
      idLibro: 1,
      contestada: false,
      pregunta: '''Según el Capítulo 1, Versículo 10... en la iglesia no sólo habían buenos creyentes; Tambien habian algunos que eran:\n'''
      '''A) Fanáticos\n'''
      '''B) Contumases\n''',
      cita: 'Tito 1:10',
      respuesta: 'B',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 21,
      idLibro: 1,
      contestada: false,
      pregunta: '''Según Tito 1:10... en la iglesia habian algunos que eran:\n'''
      '''A) Engañadores y habladores de vanidades\n'''
      '''B) Irreprensibles y calumniadores\n''',
      cita: 'Tito 1:10',
      respuesta: 'A',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 22,
      idLibro: 1,
      contestada: false,
      pregunta: '''Según Tito 1:10... en la iglesia habian algunos que eran:\n'''
      '''A) Engañadores y habladores de vanidades\n'''
      '''B) Irreprensibles y calumniadores\n''',
      cita: 'Tito 1:10',
      respuesta: 'A',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 23,
      idLibro: 1,
      contestada: false,
      pregunta: '''Pablo quería tapar la boca a algunos miembros de la iglesia en Creta. ¿Verdadero o falso?''',
      cita: 'Tito 1:11',
      respuesta: 'Verdadero',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 24,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿De qué manera debía Tito reprender a algunas personas de su congregación?''',
      cita: 'Tito 1:13',
      respuesta: 'Duramente',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 25,
      idLibro: 1,
      contestada: false,
      pregunta: '''Para los puros todo es: _____________ ?''',
      cita: 'Tito 1:15',
      respuesta: 'Puro',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 26,
      idLibro: 1,
      contestada: false,
      pregunta: '''Para los puros todo es: _____________ ?''',
      cita: 'Tito 1:15',
      respuesta: 'Puro',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 27,
      idLibro: 1,
      contestada: false,
      pregunta: '''Para los corrompidos e incrédulos (complete):\n'''
      '''A) Dios es mentiroso\n'''
      '''B) Ésta vida es pa gozarla\n'''
      '''C) Nada les es puro\n''',
      cita: 'Tito 1:15',
      respuesta: 'C',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 28,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cómo llama Pablo a aquellos que profesan conocer a Dios, pero que lo niegan con sus hechos?''',
      cita: 'Tito 1:15-16',
      respuesta: 'Corrompidos e incrédulos.',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 29,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Quiénes son descritos como "Malas Bestias", por su propio profeta?''',
      cita: 'Tito 1:12',
      respuesta: 'Los Cretenses',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 30,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cómo describe Pablo el testimonio del profeta que habló mal de los habitantes de Creta?''',
      cita: 'Tito 1:13',
      respuesta: 'Como verdadero',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 31,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cómo tienen la mente y la conciencia los incrédulos?''',
      cita: 'Tito 1:15',
      respuesta: 'Corrompida',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 32,
      idLibro: 1,
      contestada: false,
      pregunta: '''Mencione 2 características que deben tener los ancianos, según Tito 2:2''',
      cita: 'Tito 2:2',
      respuesta: 'Sobrios, serios, prudentes, sanos en la fe, en el amor, en la paciencia',
      valor: 2,
    ),
     Pregunta(
      idPregunta: 33,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Porqué las mujeres jovenes deben ser castas y prudentes?''',
      cita: 'Tito 2:5',
      respuesta: 'Para que la palabra no sea blasfemada',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 34,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cuál debía ser la exhortación de Tito para con los jovenes?''',
      cita: 'Tito 2:6',
      respuesta: 'A ser prudentes',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 35,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Debía Tito exhortar a los jovenes? Verdadero o Falso''',
      cita: 'Tito 2:6',
      respuesta: 'Verdadero',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 36,
      idLibro: 1,
      contestada: false,
      pregunta: '''Complete: Aguardando la _______ bienaventurada y la manifestación de nuestro gran _________ y _________ Jesucristo.''',
      cita: 'Tito 2:13',
      respuesta: 'Esperanza, Dios, Salvador',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 37,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cuántos capítulos tiene el libro de Tito?''',
      cita: 'Tito',
      respuesta: '3',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 38,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cuántos versículos tiene el libro de Tito?''',
      cita: 'Tito',
      respuesta: '46',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 39,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Qué cosas eran capaces de enseñar algunos miembros de la iglesia, a cambio de ganancias deshonestas?''',
      cita: 'Tito 1:11',
      respuesta: 'Lo que no conviene',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 40,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Qué debía hacer Tito con los falsos maestros de la iglesia y para qué?''',
      cita: 'Tito 1:13',
      respuesta: 'reprenderlos para que sean sanos en la fe.',
      valor: 3,
    ),
     Pregunta(
      idPregunta: 41,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿A qué cosas NO debía prestar atención Tito?''',
      cita: 'Tito 1:14',
      respuesta: 'Fábulas judaicas y mandamientos de hombres que se apartan de la verdad',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 42,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿A qué cosas NO debía prestar atención Tito?''',
      cita: 'Tito 1:14',
      respuesta: 'Fábulas judaicas y mandamientos de hombres que se apartan de la verdad',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 43,
      idLibro: 1,
      contestada: false,
      pregunta: '''Un creyente verdadero debe hablar lo que esté de acuerdo con __________ ?''',
      cita: 'Tito 2:1',
      respuesta: 'La sana doctrina',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 44,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cómo debía presentarse Tito ante los jovenes para exhortarlos?''',
      cita: 'Tito 2:7',
      respuesta: 'como ejemplo de buenas obras en todo',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 45,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿A cuáles 2 cosas nos enseña la gracia de Dios que debemos renunciar?''',
      cita: 'Tito 2:11-12',
      respuesta: 'Impiedad y deseos mundanos',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 46,
      idLibro: 1,
      contestada: false,
      pregunta: '''Explique en sus propias palabras y según Tito 3:2-3, ¿porqué debemos ser amables y mansos con todos los hombres?''',
      cita: 'Tito 3:2-3',
      respuesta: 'Porque nosotros tambien eramos en otro tiempo... como ellos',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 47,
      idLibro: 1,
      contestada: false,
      pregunta: '''Mencione 5 características que describe Pablo de algunos cristianos, ANTES de manifestarse la bondad de Dios en nosotros.''',
      cita: 'Tito 3:3',
      respuesta: 'Porque nosotros tambien éramos en otro tiempo... como ellos',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 48,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Con cuáles 2 palabras describe Pablo sus propias enseñanzas en ésta carta?''',
      cita: 'Tito 3:8',
      respuesta: 'Buenas y útiles.',
      valor: 3,
    ),
    Pregunta(
      idPregunta: 49,
      idLibro: 1,
      contestada: false,
      pregunta: '''Explique con sus propias palabras y según Tito 1:10-11, ¿Porqué razón Pablo especifica una lista de atributos y capacidades que debe cumplir un miembro de la iglesia, para poder ser nombrado ANCIANO u OBISPO?''',
      cita: 'Tito 1:10-11',
      respuesta: 'Habian falsos creyentes y maestros introducidos en la iglesia',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 50,
      idLibro: 1,
      contestada: false,
      pregunta: '''Diga las 3 características de los cretenses, según su propio profeta.''',
      cita: 'Tito 1:12',
      respuesta: 'Mentirosos, malas bestias, glotones ociosos',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 51,
      idLibro: 1,
      contestada: false,
      pregunta: '''Nombre 5 características del corrompido e incrédulo''',
      cita: 'Tito 1:15-16',
      respuesta: '---',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 52,
      idLibro: 1,
      contestada: false,
      pregunta: '''Nombre 3 características o ejemplos de conducta que debía presentar Tito, como buen maestro.''',
      cita: 'Tito 2:7-8',
      respuesta: '---',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 53,
      idLibro: 1,
      contestada: false,
      pregunta: '''Diga por cuáles 2 razones Tito y cualquier otro creyente deben dar testimonio y ejemplo de buenas obras antes, durante y después de su enseñanza.''',
      cita: 'Tito 2:8',
      respuesta: 'el adversario se averguence y no tenga nada malo que decir',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 54,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿De qué manera debemos vivir en éste siglo?''',
      cita: 'Tito 2:12',
      respuesta: 'sobria, justa y piadosamente',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 55,
      idLibro: 1,
      contestada: false,
      pregunta: '''Diga un versículo del capítulo 1 de MEMORIA, con su cita bíblica.''',
      cita: 'Tito 1',
      respuesta: '---',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 56,
      idLibro: 1,
      contestada: false,
      pregunta: '''Diga un versículo del capítulo 2 de MEMORIA, con su cita bíblica.''',
      cita: 'Tito 2',
      respuesta: '---',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 57,
      idLibro: 1,
      contestada: false,
      pregunta: '''Diga un versículo del capítulo 3 de MEMORIA, con su cita bíblica.''',
      cita: 'Tito 3',
      respuesta: '---',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 58,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Porqué Pablo anima a Tito a "insistir" con firmeza en las enseñanzas recibidas en ésta carta?''',
      cita: 'Tito 3:8',
      respuesta: 'Para que los que creen en Dios se ocupen en buenas obras.',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 59,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Porqué Pablo anima a Tito a "insistir" con firmeza en las enseñanzas recibidas en ésta carta?''',
      cita: 'Tito 3:8',
      respuesta: 'Para que los que creen en Dios se ocupen en buenas obras.',
      valor: 4,
    ),
    Pregunta(
      idPregunta: 60,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Cuál de las siguientes NO puede ser una característica de las ancianas de la iglesia?\n'''
      '''A) No esclavas del vino\n'''
      '''B) No sujetas a su marido\n'''
      '''C) Maestras del bien\n''',
      cita: 'Tito 2:3',
      respuesta: 'B.',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 61,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Quién tiene la responsabilidad de enseñar a las mujeres jovenes, según Pablo?''',
      cita: 'Tito 2:3-4',
      respuesta: 'Las ancianas',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 62,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿A quién debe amar las mujeres jovenes?\n'''
      '''A) A su marido\n'''
      '''B) A sus hijos\n'''
      '''C) A Y B\n'''
      '''D) Solamente al Señor Jesús\n''',
      cita: 'Tito 2:4',
      respuesta: 'C',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 63,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿A quién debe sujetarse las mujeres jovenes?\n'''
      '''A) A su marido\n'''
      '''B) Al projimo\n'''
      '''C) A sus padres\n'''
      '''D) A Dios Padre\n''',
      cita: 'Tito 2:5',
      respuesta: 'A',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 64,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Porqué razón las mujeres jovenes deben cuidar de sus casas, marido e hijos?''',
      cita: 'Tito 2:5',
      respuesta: 'Para que la palabra de Dios no sea blasfemada',
      valor: 2,
    ),
    Pregunta(
      idPregunta: 65,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿Debe un siervo permanecer sujeto a sus amos? Verdadero o Falso''',
      cita: 'Tito 2:9',
      respuesta: 'Verdadero',
      valor: 1,
    ),
     Pregunta(
      idPregunta: 66,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿En qué tipo de cosas debe agradar un siervo a su amo?''',
      cita: 'Tito 2:9',
      respuesta: 'En todo',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 67,
      idLibro: 1,
      contestada: false,
      pregunta: '''Cristo nos redime de toda __________?''',
      cita: 'Tito 2:14',
      respuesta: 'Iniquidad',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 68,
      idLibro: 1,
      contestada: false,
      pregunta: '''Tito debía recordarle a la iglesia que tenían que permanecer sujetos a alguien. ¿A QUIÉNES tenían que obedecer y sujetarse?''',
      cita: 'Tito 3:1',
      respuesta: 'A los gobernantes y autoridades',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 69,
      idLibro: 1,
      contestada: false,
      pregunta: '''¿A quiénes no debían difamar los creyentes de Creta?\n'''
      '''A) A nadie\n'''
      '''B) A Pablo\n'''
      '''C) A Tito\n'''
      '''D) A los Ancianos\n''',
      cita: 'Tito 3:2',
      respuesta: 'A',
      valor: 1,
    ),
    Pregunta(
      idPregunta: 70,
      idLibro: 1,
      contestada: false,
      pregunta: '''Dios nos ha justificado por:\n'''
      '''A) Nuestras buenas obras\n'''
      '''B) Amor a nuestros padres\n'''
      '''C) Su gracia\n'''
      '''D) Mi arrepentimiento\n''',
      cita: 'Tito 3:2',
      respuesta: 'C',
      valor: 1,
    ),

  ];
}
